global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus 
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI that exposes /metrics
  - job_name: 'python-mongodb-api'
    static_configs:
      - targets: ['python-mongodb-api:8000']
