class CodePrefix:

    PAYMENT = "PAY"
    INVOICE = "INV"
    
    SUPPLIER_PAYMENT = "PAY-SUP"
    SUPPLIER_INVOICE = "INV-SUP"

    CUSTOMER_PAYMENT = "PAY-CUS"
    CUSTOMER_INVOICE = "INV-CUS"

    EMPLOYEE_PAYMENT = "PAY-EMP"
    EMPLOYEE_INVOICE = "INV-EMP"

    COMPANY_INVOICE = "INV-COMP"
    COMPANY_ACCOUNT = "ACC-COMP"
    COMPANY_TRANSACTION = "TR-COMP"

    CUSTOMER_ACCOUNT = "ACC-CUS"
    CUSTOMER_TRANSACTION = "TR-CUS"

    SUPPLIER_ACCOUNT = "ACC-SUP"
    SUPPLIER_TRANSACTION = "TR-SUP"
